### ISSUE TITLE
Maven library fails with java.lang.VerifyError: Verifier rejected class ... on Android 11

### ISSUE THREAD

**Issue by M66B** [eclipse-ee4j/mail#457] opened 2020-06-14 08:23 UTC
**Describe the bug**

Library version 1.6.5 from:
https://mvnrepository.com/artifact/com.sun.mail/android-mail
https://mvnrepository.com/artifact/com.sun.mail/android-activation

```
Caused by: java.lang.VerifyError: Verifier rejected class com.sun.mail.handlers.handler_base: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors() failed to verify: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors(): [0x4]  can't resolve returned type 'Unresolved Reference: java.awt.datatransfer.DataFlavor[]' or 'Reference: javax.activation.ActivationDataFlavor[]' (declaration of 'com.sun.mail.handlers.handler_base' appears in /data/app/.../base.apk)
        at java.lang.Class.newInstance(Class.java:-2)
        at javax.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:601)
        at javax.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:573)
        at javax.activation.CommandMap.createDataContentHandler(CommandMap.java:205)
        at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:594)
        at javax.activation.DataHandler.getContent(DataHandler.java:521)
        at javax.mail.internet.MimeMessage.getContent(MimeMessage.java:1475)
```

**Smartphone:**
 - Device: Pixel 3a XL
 - OS: Android 11 beta 1

**Additional context**
The same library works without problems on Android 10.

Compiling the source inline with the app solves the issue on Android 11:
https://github.com/M66B/FairEmail/commit/286a8fd373fec8e3ed31571090b5afadc656eec3

My guess there is something wrong with the build process / published library.

**Comment by rivercartwright** [comment] 2020-09-15 05:21
The same problem exists on the released version of Android 11.

**Comment by rivercartwright** [comment] 2020-09-16 00:05
Here is my current theory as to the cause. 

The code in android-activation-1.6.5.jar doesn't match the code in the sources jar file from Maven. I think there is an error in the compilation process that causes the standard javax.activation code being used instead of the modified code in android-activation-1.6.5.jar. 

My evidence for this is when I download android-activation-1.6.5.jar from Maven central and run javap over the class DataConentHandler I see references to java.awt.datatransfer.DataFlavor. There are no such references to that class in the source code.
```
javap -classpath android-activation-1.6.5.jar javax.activation.DataContentHandler
Compiled from "DataContentHandler.java"
public interface javax.activation.DataContentHandler {
  public abstract java.awt.datatransfer.DataFlavor[] getTransferDataFlavors();
  public abstract java.lang.Object getTransferData(java.awt.datatransfer.DataFlavor, javax.activation.DataSource) throws java.awt.datatransfer.UnsupportedFlavorException, java.io.IOException;
  public abstract java.lang.Object getContent(javax.activation.DataSource) throws java.io.IOException;
  public abstract void writeTo(java.lang.Object, java.lang.String, java.io.OutputStream) throws java.io.IOException;
}
```

**Comment by rivercartwright** [comment] 2020-09-16 00:06
I suspect that the reason why this fails on Android 11 is that Android 11 might be less lenient of references to these non existent classes.

**Comment by rivercartwright** [comment] 2020-09-21 00:37
I have a convoluted workaround for this problem. It's temporary.

I switched to using the release candidates of the Eclipse Jakarta Mail and Activation components.
```
    implementation 'com.sun.mail:jakarta.mail:2.0.0-RC6'
    implementation 'com.sun.activation:jakarta.activation:2.0.0-RC3'
```

However, there is a bug in the pom.xml metadata of the activation library that prevents Android from compiling it. 
https://github.com/eclipse-ee4j/jaf/issues/53

While I wait for a fix to be incorporated and published I was able to unjar the activation jar, fix the pom.xml, jar it up again and then use it directly.
```
    implementation('com.sun.mail:jakarta.mail:2.0.0-RC6') {
        // This exclusion and the inclusion of the modified jar below are to work around
        // an error in the pom.xml metadata. https://github.com/eclipse-ee4j/jaf/issues/53
        exclude group: 'com.sun.activation', module: 'jakarta.activation'
    }
    implementation files('libs/jakarta.activation-2.0.0-RC3-mymod1.jar')
```

**Comment by lukasj** [comment] 2021-01-15 01:26
same as #489, closing in favor of that one (has more comments...)

**Closed by lukasj** 2021-01-15 01:26 UTC
