### ISSUE TITLE
OAuth2 POP3 Support for Microsoft

### ISSUE THREAD

**Issue by craigsha** [eclipse-ee4j/mail#461] opened 2020-07-20 01:22 UTC
**Describe the bug**
We've been able to successfully use the OAuth support for Gmail for both IMAP and POP (from our feature request https://github.com/eclipse-ee4j/mail/issues/416) thank you for adding this support. But we have been unsuccessful with POP3 on Microsoft (IMAP does work though). I have reached out to Microsoft to try and work out why and noticed that to authenticate with POP on their platform you need to send the request with two commands, which I think may be why this does not work? From the Google docs it does not look like you need to split the auth command up. Should this work? 

See comments on this community post for additional information: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-oauth-support-for-pop-in-exchange-online/ba-p/1406600

Also: https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#pop-protocol-exchange

This appears to be different to how the Google authentication works (though they should be following the same [Authentication protocol](https://tools.ietf.org/html/rfc1734#ref-IMAP4-AUTH): https://developers.google.com/gmail/imap/xoauth2-protocol

**To Reproduce**
Create a mail client which connects to Microsoft exchange (outlook.office365.com) using OAuth with POP. 
Error received: `Unable to connect to the server at outlook.office365.com due to the following exception: javax.mail.AuthenticationFailedException: Protocol error. Connection is closed. 10` 

Here is the debug logs
DEBUG: Jakarta Mail version 1.6.5
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: Providers Listed By Protocol: {imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]
DEBUG POP3: mail.pop3s.rsetbeforequit: false
DEBUG POP3: mail.pop3s.disabletop: false
DEBUG POP3: mail.pop3s.forgettopheaders: false
DEBUG POP3: mail.pop3s.cachewriteto: false
DEBUG POP3: mail.pop3s.filecache.enable: false
DEBUG POP3: mail.pop3s.keepmessagecontent: false
DEBUG POP3: mail.pop3s.starttls.enable: false
DEBUG POP3: mail.pop3s.starttls.required: false
DEBUG POP3: mail.pop3s.finalizecleanclose: false
DEBUG POP3: mail.pop3s.apop.enable: false
DEBUG POP3: mail.pop3s.disablecapa: false
DEBUG POP3: connecting to host "outlook.office365.com", port 995, isSSL true
+OK The Microsoft Exchange POP3 service is ready. [UwBZAFkAUAAyADgAMgBDAEEAMAAwADAANQAuAEEAVQBTAFAAMgA4ADIALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
CAPA
+OK
TOP
UIDL
SASL PLAIN XOAUTH2
USER
.
DEBUG POP3: Attempt to authenticate using mechanisms: XOAUTH2
DEBUG POP3: Using mechanism XOAUTH2
DEBUG POP3: AUTH XOAUTH2 command trace suppressed
DEBUG POP3: AUTH XOAUTH2 failed

javax.mail.AuthenticationFailedException: Protocol error. Connection is closed. 10
        at com.sun.mail.pop3.POP3Store.protocolConnect(POP3Store.java:193)
        at javax.mail.Service.connect(Service.java:342)
        at javax.mail.Service.connect(Service.java:222)
        at javax.mail.Service.connect(Service.java:243)

**Expected behavior**
Ability to connect to Microsoft using POP3 with OAuth.

**Mail server:**
 - Protocol being used: pop3
 - Vendor/product: Microsoft Exchange
 - Mail service URL: outlook.office365.com

Let me know your thoughts on this and if you need any more information. 

Thanks,
Craig.

**Comment by anand-vashishtha** [comment] 2020-07-28 09:30
@craigsha 
I found the solution which is working properly.

Add below scope 

"https://outlook.office.com/POP.AccessAsUser.All" explicitly in the code during acquire token.

**Comment by Viktorhe** [comment] 2020-08-10 02:54
The issue is not on the scope but on how to authenticate on Microsoft 365 POP3.
Other or standard POP3 OAuth2 authentication is 1 line format.
**[connection begins]
C: AUTH XOAUTH2 	dXNlc..==
S: +OK User successfully authenticated.**	

But connection on Microsoft 365 POP3 uses 2 lines format.
**[connection begins]
C: AUTH XOAUTH2 	
S: +	
C: dXNlc..==
S: +OK User successfully authenticated.**

**Comment by lukasj** [comment] 2021-01-18 13:55
hopefully fixed by #477

**Closed by lukasj** 2021-01-18 13:55 UTC

**Comment by kguelzau** [comment] 2021-02-16 12:04
There will be no patches to the 1.6.x (javax) branch, right?
Is there a place to see the date of the next planned (2.x) release?

**Comment by bgunics-talend** [comment] 2022-07-20 17:18
Hello,

Would anyone be able to share which Oauth flow / scope was used with this feature? Were you able to send e-mails or it was only capable to receive e-mails?
Looking at this feature as Microsoft will deactive the Basic auth for certain services: https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-may-2022/ba-p/3301866 
They have released a new Oauth flow: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-oauth-2-0-client-credentials-flow-support-for-pop-and/bc-p/3565713 
As there's no clear guide on the microsoft side it's quite a challenge to configure everything.

And it looks that SMTP is not yet included by them which is what we're really after.

**Comment by guddu9211** [comment] 2022-07-29 08:57
> @anand-vashishtha  As you suggested that adding the scope "https://outlook.office.com/POP.AccessAsUser.All" explicitly in the code during acquire token will heal this problem.

If possible, can you please share the code snippet denoting how you have added this scope in your program.

I have tried multiple combinations of adding this scope in my **Java code,** but none of them works.

**Comment by nisaanwaar** [comment] 2024-11-15 06:29
Was anybody able to resolve this? We are trying to use POP3 in our client credentials oauth2 flow but getting the same error as mentioned in post.
